### ISSUE TITLE
Curve units

### ISSUE THREAD

**Issue by ledlou** [pddasig/Machine-Learning-Competition-2021#4]
In Data Description section of Tutorial Jupyter notebook, please use the correct units for the following curves:

DTC/DTS: nanosecond per foot --> microseconds per foot
PEF: Barn --> barns/e
RDEP/RMED: Ohm per meter --> Ohm.m
+
BVW may not be part of datasets? (also it is product of porosity and water saturation anyway, not independent curve)

Cheers!

**Comment by leifoo** [comment]
Thanks. They are fixed now.
