### ISSUE TITLE
Hidden dataset constraints

### ISSUE THREAD

**Issue by ledlou** [pddasig/Machine-Learning-Competition-2021#5]
Hi there,

Could you please check if your hidden dataset (PHIF, VSH and SW) contains data outside physical limits, i.e. SW must be between 0 and 1 but many petrophysical SW model gives >1 SW values. (I suppose that your hidden dataset is from real petrophysical workflow)
The reason for asking because our algorithm will control physical constraints and if a maximum SW with 1 value is compared to >1 value in certain depth levels, that may cause false/apparent error surplus.

Thank you!

**Comment by leifoo** [comment]
Hidden dataset is between 0 and 1
